### ISSUE TITLE
During training, GPU usage is very low. 

### ISSUE THREAD

**Issue by Jiakui** [pencoa/PCNN#2]
Hi , I noticed that during the training process, GPU usage is very low, around 10%.  We are using 1080 Ti. 

How should we improve the situation? I believe that higher GPU usage should means faster training process.

**Comment by pencoa** [comment]
Thank you for your reporting.  
There are several ways to speed up with GPU. 
1. Add define device in code.  
2. Increase batch size.

Unfortunately, I don't have any GPU supporting tf and unable to test code.  
Maybe you can try it by yourself.  
Good luck.
